# Generated by Django 5.0.3 on 2024-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_uploadfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='created_by',
            field=models.TextField(default=''),
        ),
    ]
