# Generated by Django 5.0.3 on 2024-07-17 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_fileinfo_json_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
