# Generated by Django 5.0.3 on 2024-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity1', models.TextField()),
                ('relationship', models.TextField()),
                ('entity2', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Triples',
            },
        ),
    ]
