# Generated by Django 5.0.3 on 2024-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_fileinfo_alter_uploadfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_text',
            field=models.TextField(default=''),
        ),
    ]
