# Generated by Django 5.0.3 on 2024-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_texts_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='json_created',
            field=models.JSONField(default=dict),
        ),
    ]
