# Generated by Django 5.0.3 on 2024-05-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_alter_texts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='json_created',
            field=models.JSONField(default=''),
        ),
    ]
